/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ds_proje2_3;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Ebrar Yıldız
 */
public class Ebrar_Fatma_NewJFrame1 extends javax.swing.JFrame {

    private Ebrar_Fatma_BinarySearchTree bst;
    final Ebrar_Fatma_IgnoreWordsHandler ignoreHandler;

    /**
     * Creates new form NewJFrame1
     */
    public Ebrar_Fatma_NewJFrame1() {
        initComponents();
        setTitle("Mini Desktop Search Engine");
        bst = new Ebrar_Fatma_BinarySearchTree();
        ignoreHandler = new Ebrar_Fatma_IgnoreWordsHandler();
        jFileChooser1.setMultiSelectionEnabled(true);
        btn_search.setEnabled(false);
        JOptionPane.showMessageDialog(null, "İŞLEM YAPMAK İSTEDİĞİNİZ DOSYALARI SEÇİNİZ ");
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_search = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_sonuc = new javax.swing.JTextArea();
        btn_search = new javax.swing.JButton();
        cmbx = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_search2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(846, 450));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(846, 450));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(846, 450));

        jPanel1.setBackground(new java.awt.Color(231, 205, 232));
        jPanel1.setMaximumSize(new java.awt.Dimension(846, 450));
        jPanel1.setMinimumSize(new java.awt.Dimension(846, 450));
        jPanel1.setPreferredSize(new java.awt.Dimension(846, 450));

        jFileChooser1.setCurrentDirectory(null);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        txt_search.setEditable(false);
        txt_search.setColumns(20);
        txt_search.setRows(5);
        txt_search.setText("\n");
        jScrollPane1.setViewportView(txt_search);

        txt_sonuc.setEditable(false);
        txt_sonuc.setColumns(20);
        txt_sonuc.setRows(5);
        txt_sonuc.setText("\n");
        jScrollPane2.setViewportView(txt_sonuc);

        btn_search.setBackground(new java.awt.Color(153, 0, 204));
        btn_search.setText("SEARCH");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        cmbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PreOrder", "PostOrder", "InOrder", "" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Please choose an order");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbx, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_search)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbx, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        jTabbedPane1.addTab("numbers of the words in each file", jPanel1);

        jPanel2.setBackground(new java.awt.Color(231, 205, 232));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Enter the name  you want to search in all files");

        btn_search2.setBackground(new java.awt.Color(255, 153, 255));
        btn_search2.setText("SEARCH");
        btn_search2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btn_search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search2ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\n");
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btn_search2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_search2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("find the frequency of a word", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().equals(JFileChooser.APPROVE_SELECTION)) {
            File[] selectedFiles = jFileChooser1.getSelectedFiles(); // Birden fazla dosyayı seçmek için getSelectedFiles kullandık
            StringBuilder allText = new StringBuilder(); // Tüm dosyaların içeriğini birleştirmek için StringBuilder oluşturduk
            for (File selectedFile : selectedFiles) {
                try {
                    BufferedReader reader = new BufferedReader(new FileReader(selectedFile));
                    StringBuilder text = new StringBuilder();
                    String line;
                    while ((line = reader.readLine()) != null) {
                        allText.append(line).append("\n");
                    }
                    reader.close();
                    txt_search.setText(text.toString()); // Dosya içeriğini metin alanına yapıştırma               
                } catch (IOException ex) {
                    
                }
            }
            // Tüm dosyaların içeriğini birleştirerek metin alanını güncelledik
            txt_search.setText(allText.toString());
        }
        btn_search.setEnabled(true);
    }//GEN-LAST:event_jFileChooser1ActionPerformed
 
    
    
    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        bst.clear();
        
        JOptionPane.showMessageDialog(null, 
                "İŞLEME ALINMAYACAK KELİMELER İÇİN İGNORELİST SEÇİNİZ ");
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(null);
        File file = new File(fileChooser.getSelectedFile().getPath());
        Ebrar_Fatma_IgnoreWordsHandler<String> ignoreHandler = new Ebrar_Fatma_IgnoreWordsHandler<>();
        Ebrar_Fatma_MyLinkedList<String> ignoreWords = Ebrar_Fatma_IgnoreWordsHandler.readLinesFromFile(file);
        ignoreHandler.addToIgnoreList(ignoreWords);
        String selectedTraversal = cmbx.getSelectedItem().toString();
        String content = txt_search.getText(); // Sadece harfleri ve boşlukları al
        String[] words = content.split("\\s+"); // Boşluklara göre ayır
        for (String word : words) {
            word = word.toLowerCase(); // Sadece harfleri al
            if (!ignoreHandler.contains(word) && !word.contains("<") 
                    && !word.contains(".") && !word.contains(",")) {
                bst.addWord(word);
            }
        }

    switch (selectedTraversal) {
        case "PreOrder":
            String preorderResult = bst.preorderTraversal();
            txt_sonuc.setText("PreOrder traversel:\n" + preorderResult);
            break;
        case "PostOrder":
            String postOrder = bst.postorderTraversal();
            txt_sonuc.setText("PostOrder traversel:\n" + postOrder);
            break;
        case "InOrder":
            String inOrder = bst.inorderTraversal();
            txt_sonuc.setText("InOrder traversel:\n" + inOrder);
            break;
        default:
            System.out.println("Invalid traversal type");
            break;
    }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search2ActionPerformed
       String wordToSearch = jTextField1.getText(); 
    if (!wordToSearch.isEmpty()) { 
        StringBuilder result = new StringBuilder(); 
        File[] selectedFiles = jFileChooser1.getSelectedFiles(); 
        for (File file : selectedFiles) { 
            if (file.isFile() && file.getName().endsWith(".html")) { 
                try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
                    String line;
                    bst = new Ebrar_Fatma_BinarySearchTree(); 
                    while ((line = reader.readLine()) != null) {
                        String[] words = line.split("\\s+"); 
                        for (String word : words) {
                            word = word.toLowerCase(); 
                            if (word.equals(wordToSearch)) {
                                bst.addWord(word); 
                            }
                        }
                    }
                    int occurrencesInFile = bst.search(wordToSearch); 
                    result.append("File: ").append(file.getName()).append(", Occurrences: ").
                            append(occurrencesInFile).append("\n"); 
                } catch (IOException ex) {
                    ex.printStackTrace(); 
                }
            }
        }
        jTextArea1.setText("THE WORD : " + wordToSearch + "\n" + result.toString()); 
    }
    }//GEN-LAST:event_btn_search2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ebrar_Fatma_NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ebrar_Fatma_NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ebrar_Fatma_NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ebrar_Fatma_NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ebrar_Fatma_NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_search2;
    private javax.swing.JComboBox<String> cmbx;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea txt_search;
    private javax.swing.JTextArea txt_sonuc;
    // End of variables declaration//GEN-END:variables
}
